# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci_cd:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      with:
        # The Poetry version to install
        version: 1.7.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: poetry install
    - name: Test
      run: poetry run task test
    - name: Lint
      run: poetry run task lint
    - name: Formatting
      run: poetry run task formatter
    - name: Security
      run: poetry run task security
